version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --region ap-south-1 --no-include-email)
      
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"      
      - mvn clean install
      - docker build -t build -t audit-auth-registry .
      - docker tag audit-auth-registry:latest 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-auth-registry:latest
  post_build:  
    commands:
      - echo "Post_build"
      - docker push 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-auth-registry:latest
      - printf '[{"name":"audit-auth-container","imageUri":"%s"}]' 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-auth-registry:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  


