version: 0.2

phases:
  install:
    runtime-versions:      
      java: corretto17
      
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --region ap-south-1 --no-include-email)
      
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"     
      - cd Audit-Checklist-microservice 
      - mvn clean install -DskipTests
      - docker build -t audit-checklist-registry .
      - docker tag audit-checklist-registry:latest 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-checklist-registry:latest
  post_build:  
    commands:
      - echo "Post_build"
      - docker push 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-checklist-registry:latest
      - printf '[{"name":"audit-checklist-container","imageUri":"%s"}]' 249113955330.dkr.ecr.ap-south-1.amazonaws.com/audit-checklist-registry:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - Audit-Checklist-microservice/imagedefinitions.json
  


