version: 0.2

phases:
  install:
    runtime-versions:      
      java: corretto8
      
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --region ap-south-1 --no-include-email)
      
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"      
      - mvn clean install -DskipTests
      - docker build -t c15-audit-benchmark-repo .
      - docker tag c15-audit-benchmark-repo:latest 249113955330.dkr.ecr.ap-south-1.amazonaws.com/c15-audit-benchmark-repo:latest
  post_build:  
    commands:
      - echo "Post_build"
      - docker push 249113955330.dkr.ecr.ap-south-1.amazonaws.com/c15-audit-benchmark-repo:latest
      - printf '[{"name":"audit-benchmark-container","imageUri":"%s"}]' 249113955330.dkr.ecr.ap-south-1.amazonaws.com/c15-audit-benchmark-repo:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  


